### ISSUE TITLE
question How does this plugin work?

### ISSUE THREAD

**Issue by WSrujan** [NurMarvin/better-threads#1]
Will this plugin show all threads instead for finding for threads in every channel?
Ability to see all threads in one go

**Comment by NurMarvin** [comment]
Currently the plugin only allows you to change your default notification settings when you create or join a thread. I could try adding some kind of modal or popout which shows all threads for all channels but I would need to look more into how the client gets the specific threads for channels to see if it would be feasable without spamming Discord's API with requests since that would make the plugin way more risky to use.

**Comment by NurMarvin** [comment]
It seems Discord is adding this themselves soon
